import { View, Text } from 'react-native'
import React from 'react'

const ExploreList = () => {
  return (
    <View>
      <Text>Safe Area2222</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
      <Text>ExploreList</Text>
    </View>
  )
}

export default ExploreList